name = "PointSpreadFunctions"
uuid = "e8810a93-244e-46c5-8da3-35c5dd956001"
authors = ["Rainer Heintzmann (rheintzmann) <heintzmann@gmail.com>"]
version = "0.3"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
IndexFunArrays = "613c443e-d742-454e-bfc6-1d7f8dd76566"
NDTools = "98581153-e998-4eef-8d0d-5ec2c052313d"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ZernikePolynomials = "e462d300-c971-11e9-30f1-fb93b1f8f73a"

[compat]
FFTW = "1.4, 1.5"
IndexFunArrays = "0.2"
NDTools = "0.6"
QuadGK = "2"
FourierTools = "0.4"
SpecialFunctions = "1, 2"
ZernikePolynomials = "0.1"
julia = "1, 1.6, 1.7, 1.8"

[extras]
NDTools = "98581153-e998-4eef-8d0d-5ec2c052313d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NDTools"]
