[deps]
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NDTools = "98581153-e998-4eef-8d0d-5ec2c052313d"
Napari = "ed46c112-542a-4e7e-ab0f-e39321fab6f0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PointSpreadFunctions = "e8810a93-244e-46c5-8da3-35c5dd956001"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
